version: '3'
services:
    # Odoo
    odoo:
        build:
            context: .
            dockerfile: odoo.Dockerfile
        # container_name: odoo
        # image: odoo
        # command: bash -c "chown -R 101:101 filestore && chmod -R 750 filestore"
        restart: always
        networks:
            - odoo-default
        volumes:
            - ./addons:/mnt/extra-addons
            - ./config/odoo:/etc/odoo
            ## for HA ##
            - odoo_data:/var/lib/odoo
            # - odoo_data:/root/.local/share/Odoo
        links:
            - db:db
        ports:
            - "8070-8072:8069"
        depends_on:
            - db
        deploy:
            replicas: 3
    
    # # NGINX
    nginx:
        build: .
        container_name: nginx
        image: nginx
        restart: always
        networks:
            - odoo-default
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./config/nginx:/etc/nginx/conf.d
        depends_on:
            - odoo
        expose:
            - 80

    # Postgres
    db:
        container_name: db
        image: postgres:13
        restart: always
        environment:
            POSTGRES_PASSWORD: odoo
            POSTGRES_HOST_AUTH_METHOD: trust

        networks:
            - odoo-default
        volumes:
            - ./postgresql:/docker-entrypoint-initdb.d/
    
volumes:
    odoo_data:
    postgresql:

networks:
    odoo-default:
        external: true