version: '3'
services:
    # Odoo
    odoo:
        build:
            context: .
            dockerfile: odoo.Dockerfile
        restart: always
        volumes:
            - odoo_data:/opt/odoo/.local/share/Odoo
        links:
            - db:db
        # ports:
        #     - 8069
        depends_on:
            - db
        deploy:
            replicas: 2
        tty: true
    
    # # NGINX
    nginx:
        build: .
        container_name: nginx
        image: nginx
        # restart: always
        ports:
            - 80:80
        volumes:
            - ./config/nginx:/etc/nginx/conf.d
        expose:
            - 80
        depends_on:
            - odoo

    # Postgres
    db:
        container_name: db
        image: postgres:13
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: odoo
            POSTGRES_HOST_AUTH_METHOD: trust
        ports:
            - '5555:5432'
        volumes:
            - ./postgresql:/docker-entrypoint-initdb.d/
        tty: true
    
volumes:
    odoo_data:
    postgresql: